package loadbalancer.enums;

public enum LoadBalanceStrategy {
    RANDOM,
    ROUND_ROBIN,
    HASH,
    LEAST_RESPONSE_TIME,
    LEAST_CONNECTIONS,
    WEIGHTED,
    WEIGHTED_ROUND_ROBIN,
    DYNAMIC_WEIGHTED_ROUND_ROBIN,
    DYNAMIC_WEIGHTED_ROUND_ROBIN_LEAST_CONNECTIONS,
    PEAK_EXPONENTIALLY_WEIGHTED_MOVING_AVERAGE;
}
