package chess.enums;

public enum GameStatus {
    ACTIVE,
    WHITE_WIN,
    BLACK_WIN,
    WHITE_WIN_BY_RESIGNATION,
    BLACK_WIN_BY_RESIGNATION,
    DRAW_DUE_TO_INSUFFICIENT_MATERIAL,
    WHITE_WIN_BY_STALE_MATE,
    BLACK_WIN_BY_STALE_MATE,
}
